// ************** This file is automatically generated. Any modifications will be lost ************************

import {config} from '@parischap/configs/VitestConfigSource';
export default config('configs')