/**
 * Module that serves as a base for all Package types (see README.md and Package.ts). This module
 * does not define a constructor as no object implementing this interface will exist
 */
/* This module must not import any external dependency. It must be runnable without a package.json because it is used by the generate-config-files.ts bin */

import { join } from 'path';
import {
  configFilename,
  readMeFilename,
  viteTimeStampFilenamePattern,
} from '../../shared-utils/constants.js';
import { Data, Record } from '../../shared-utils/types.js';
import { readJsonFile, toMiniGlobRegExp } from '../../shared-utils/utils.js';
import * as ConfigFiles from '../ConfigFiles.js';

/**
 * Module tag
 *
 * @category Module markers
 */
const _moduleTag = '@parischap/configs/internal/bin-utils/Package/Base/';

/**
 * Symbol used for the `externalConfigurationFiles` property
 *
 * @category Models
 */
export const externalConfigurationFilesSymbol: unique symbol = Symbol.for(
  _moduleTag + 'externalConfigurationFiles/',
);

/**
 * Symbol used for the `toPackageFiles` property
 *
 * @category Models
 */
export const toPackageFilesSymbol: unique symbol = Symbol.for(_moduleTag + 'toPackageFiles/');

// List of files which can be in a package although not generated by the configs package
export const externalConfigurationFilesDefault = toMiniGlobRegExp([
  readMeFilename,
  configFilename,
  viteTimeStampFilenamePattern,
]);

/**
 * Type of a Base
 *
 * @category Models
 */
// This object is not marked because it is not meant to be built
export interface Type {
  /** Name of the package */
  readonly name: string;
  /** Relative path to the package root */
  readonly path: string;
  /**
   * RegExp that matches configuration files that are allowed to be in the package although not
   * generated by the configs package
   */
  readonly [externalConfigurationFilesSymbol]: RegExp;
  /** Generates the PackageFiles for `self` */
  readonly [toPackageFilesSymbol]: (exportsFilesOnly: boolean) => Promise<ConfigFiles.Type>;
}

/**
 * Reads the configuration file of `self`
 *
 * @category Destructors
 */
export const readConfigFile = async (self: Data<Type>): Promise<Record> =>
  readJsonFile(join(self.path, configFilename));
