/** This config is the one to be used in the sub-package of a monorepo. */
// This module must not import any external dependency. It must be runnable without a package.json
import type { Config, ReadonlyStringArray, ReadonlyStringRecord } from '../types.js';
import { deepMerge, makeConfigWithLocalInternalDependencies } from '../utils.js';
import configInternalBase from './configInternalBase.js';
import configInternalProject from './configInternalProject.js';

export default ({
  repoName,
  packageName,
  description,
  dependencies = {},
  devDependencies = {},
  peerDependencies = {},
  examples = [],
  scripts = {},
  environment,
  buildMethod,
  isPublished,
  hasDocGen,
  keywords = [],
  useEffectAsPeerDependency,
  useEffectPlatform = 'No',
  prefixForAutogeneratedIndex,
}: {
  readonly repoName: string;
  readonly packageName: string;
  readonly description: string;
  readonly dependencies?: ReadonlyStringRecord;
  readonly devDependencies?: ReadonlyStringRecord;
  readonly peerDependencies?: ReadonlyStringRecord;
  readonly examples?: ReadonlyStringArray;
  readonly scripts?: ReadonlyStringRecord;
  readonly environment: string;
  readonly buildMethod: string;
  readonly isPublished: boolean;
  readonly hasDocGen: boolean;
  readonly keywords?: ReadonlyStringArray;
  readonly useEffectAsPeerDependency: boolean;
  readonly useEffectPlatform?: string;
  readonly prefixForAutogeneratedIndex: string;
}): Config =>
  makeConfigWithLocalInternalDependencies({
    repoName,
    packageName,
    onlyAllowDevDependencies: false,
    allowWorkspaceSources: true,
    config: deepMerge(
      configInternalBase({
        packageName,
        description,
        environment,
        scripts,
      }),
      configInternalProject({
        packageName,
        repoName,
        dependencies,
        devDependencies,
        peerDependencies,
        examples,
        buildMethod,
        isPublished,
        hasDocGen,
        keywords,
        useEffectAsPeerDependency,
        useEffectPlatform,
        prefixForAutogeneratedIndex,
      }),
    ) as Config,
  });
