/** This config is the one to be used in the sub-package of a monorepo. */
// This module must not import any external dependency. It must be runnable without a package.json
import type { Config, PackageWithSourceConfigParameters } from '../shared-utils/types.js';
import { deepMerge } from '../shared-utils/utils.js';
import configInternalBase from './configInternalBase.js';
import configInternalWithSource from './configInternalWithSource.js';

export default ({
  repoName,
  subRepoName,
  description,
  dependencies,
  devDependencies,
  peerDependencies,
  examples,
  scripts,
  environment,
  buildMethod,
  isPublished,
  hasDocGen,
  keywords,
  useEffectAsPeerDependency,
  useEffectPlatform,
  packagePrefix,
  autogeneratedIndexTs,
  autogeneratedImports,
}: PackageWithSourceConfigParameters & {
  readonly subRepoName: string;
  readonly repoName: string;
}): Config =>
  deepMerge(
    configInternalBase({
      packageName: subRepoName,
      description,
      scripts,
      isConfigsPackage: false,
    }),
    configInternalWithSource({
      packageName: subRepoName,
      repoName,
      dependencies,
      devDependencies,
      peerDependencies,
      examples,
      buildMethod,
      environment,
      isPublished,
      hasDocGen,
      keywords,
      useEffectAsPeerDependency,
      useEffectPlatform,
      packagePrefix,
      isConfigsPackage: false,
      autogeneratedIndexTs,
      autogeneratedImports,
    }),
  ) as Config;
