// This module has been placed directly under esm so it gets exports sugar in package.json. This allows importing it from vitest.config.ts and prettier.config.ts which are not capable of importing a .ts extension because they use Node with the --experimental-transform-types flag
// This module must not import any external dependency. It must be runnable without a package.json
import { join } from 'path';

export const owner = 'parischap';
export const scope = '@' + owner;
export const devScope = scope + '-dev';
export const slashedScope = scope + '/';
export const slashedDevScope = devScope + '/';

export const packageManager = `pnpm@10.27.0`;

export const versionControlService = 'github.com';

export const srcMark = 'esm';
export const testsMark = 'tests';
export const examplesMark = 'examples';
export const othersMark = 'others';

export const docgenMark = 'docgen';

export const tsExecuter = 'jiti';

export const configsPackageName = 'configs';

export const indexBareName = 'index';
export const testsIndexBaseName = `${indexBareName}.tests`;

export const githubWorkflowsPublishFilename = 'publish.yml';
export const githubWorkflowsPagesFilename = 'pages.yml';
export const docsIndexMdFilename = `${indexBareName}.md`;
export const indexTsFilename = `${indexBareName}.ts`;
export const testsIndexFilename = `${testsIndexBaseName}.ts`;
export const docsConfigYmlFilename = '_config.yml';
export const docgenConfigFilename = 'docgen.json';
export const gitIgnoreFilename = '.gitignore';
export const formatterIgnoreFilename = '.prettierignore';
export const packageJsonFilename = 'package.json';
export const tsConfigBaseFilename = 'tsconfig.base.json';
export const tsConfigFilename = 'tsconfig.json';
export const tsConfigDocGenFilename = `tsconfig.${docgenMark}.json`;
export const tsConfigSrcFilename = `tsconfig.${srcMark}.json`;
export const tsConfigTestsFilename = `tsconfig.${testsMark}.json`;
export const tsConfigExamplesFilename = `tsconfig.${examplesMark}.json`;
export const tsConfigOthersFilename = `tsconfig.${othersMark}.json`;
export const projectConfigFilename = 'project.config.json';
export const formatterConfigFilename = '.prettierrc.json';
export const linterConfigFilename = 'eslint.config.ts';
export const madgeConfigFilename = '.madgerc';
export const readMeFilename = 'README.md';
export const licenseFilename = 'LICENSE';
export const pnpmWorkspaceFilename = 'pnpm-workspace.yaml';
export const pnpmLockFilename = 'pnpm-lock.yaml';
export const actionFilename = 'action.yml';
export const viteConfigFilename = 'vite.config.ts';
export const viteTimeStampFilenamePattern = 'vite.config.ts.timestamp-*.mjs';
export const vitestConfigFilename = 'vitest.config.ts';

export const internalFolderName = 'internal';
export const tsBuildInfoFolderName = '.tsbuildinfo';
export const sourceFolderName = srcMark;
export const examplesFolderName = examplesMark;
export const testsFolderName = testsMark;
export const othersFolderName = othersMark;
export const prodFolderName = 'dist';
export const typesFolderName = 'dts';
export const commonJsFolderName = 'cjs';
export const binariesFolderName = 'bin';
export const npmFolderName = 'node_modules';
export const gitFolderName = '.git';
export const packagesFolderName = 'packages';
export const starterFolderName = 'init';
export const githubFolderName = '.github';
export const workflowsFolderName = 'workflows';
export const actionsFolderName = 'actions';
export const docsFolderName = 'docs';
export const docgenFolderName = 'modules';
export const readmeAssetsFolderName = 'readme-assets';
export const templatesFolderName = 'templates';

/* This path is used to read in the assets directory and as key in a ConfigFiles object. It must therefore use the system path separator */
export const githubWorkflowsPublishPath = join(
  githubFolderName,
  workflowsFolderName,
  githubWorkflowsPublishFilename,
);

/* This path is used to read in the assets directory and as key in a ConfigFiles object. It must therefore use the system path separator */
export const githubWorkflowsPagesPath = join(
  githubFolderName,
  workflowsFolderName,
  githubWorkflowsPagesFilename,
);

/* This path is used as key in a ConfigFiles object. It must therefore use the system path separator */
export const indexTsPath = join(sourceFolderName, indexTsFilename);

/* This path is used as key in a ConfigFiles object. It must therefore use the system path separator */
export const docsIndexMdPath = join(docsFolderName, docsIndexMdFilename);

/* This path is used as key in a ConfigFiles object. It must therefore use the system path separator */
export const docsConfigYmlPath = join(docsFolderName, docsConfigYmlFilename);

// packagesFolderName is not a folder generated by a third party but it is added to avoid recursion
export const foldersGeneratedByThirdParties = [
  gitFolderName,
  prodFolderName,
  tsBuildInfoFolderName,
  npmFolderName,
  packagesFolderName,
];

export const foldersWithoutConfigFiles = [
  ...foldersGeneratedByThirdParties,
  sourceFolderName,
  examplesFolderName,
  testsFolderName,
  readmeAssetsFolderName,
];

export const filesGeneratedByThirdParties = [viteTimeStampFilenamePattern, pnpmLockFilename];

export const binariesPath = `${npmFolderName}/${slashedScope}${configsPackageName}/${sourceFolderName}/${binariesFolderName}`;

export const allFilesPattern = '**/*';
const allFilesInMd = allFilesPattern + '.md/*';

export const jsExtensions = ['.js', '.mjs', '.cjs'];
export const tsExtensions = ['.ts', '.mts', '.cts'];
export const javaScriptExtensions = [...jsExtensions, ...tsExtensions];
export const htmlExtensions = ['.html', '.htm'];
export const mdExtensions = ['.md'];
export const simpleJsonExtensions = ['.json'];
export const jsoncExtensions = ['.jsonc', '.code-workspace'];
export const json5Extensions = ['.json5'];
export const jsonExtensions = [...simpleJsonExtensions, ...jsoncExtensions, ...json5Extensions];
export const ymlExtensions = ['.yml', '.yaml'];

export const tsConfigStyleIncludeForSourceFiles = `${sourceFolderName}/${allFilesPattern}`;
export const tsConfigStyleIncludeForTestsFiles = `${testsFolderName}/${allFilesPattern}`;
export const tsConfigStyleIncludeForExampleFiles = `${examplesFolderName}/${allFilesPattern}`;

export const eslintStyleIncludeForSourceFiles = javaScriptExtensions.map(
  (extension) => `${sourceFolderName}/${allFilesPattern}${extension}`,
);
export const eslintStyleExcludeForSourceFiles = `${sourceFolderName}/**`;

const prefixWith =
  (prefix: string) =>
  (as: ReadonlyArray<string>): Array<string> =>
    as.map((a) => prefix + a);
const prefixWithAllFilePatterns = prefixWith(allFilesPattern);
export const allTsFiles = prefixWithAllFilePatterns(tsExtensions);
export const allJavaScriptFiles = prefixWithAllFilePatterns(javaScriptExtensions);
export const allHtmlFiles = prefixWithAllFilePatterns(htmlExtensions);
export const allMdFiles = prefixWithAllFilePatterns(mdExtensions);
export const allSimpleJsonFiles = prefixWithAllFilePatterns(simpleJsonExtensions);
export const allJsoncFiles = prefixWithAllFilePatterns(jsoncExtensions);
export const allJson5Files = prefixWithAllFilePatterns(json5Extensions);
export const allYmlFiles = prefixWithAllFilePatterns(ymlExtensions);
export const allJsInMdFiles = prefixWith(allFilesInMd)(javaScriptExtensions);

/* Do not use carret at start of dependency versions because we could end up with different versions in the diverse projects. Set one version and update it regularly */
export const effectDependencies = {
  effect: '3.19.6',
};

export const effectPlatformDependencies = {
  '@effect/platform': '0.93.3',
  '@effect/platform-node': '0.101.1',
  '@effect/cluster': '0.53.4',
  '@effect/rpc': '0.72.2',
  '@effect/sql': '0.48.0',
  '@effect/workflow': '0.13.0',
};

export const docGenDependencies = {
  '@effect/docgen': '0.5.2',
  // Used by docgen as peerDependency
  tsx: '4.20.6',
};

/* Add here all dependencies used by modules exported in index.ts that are not used by other by the other packages */
export const configsDependencies = {
  // Used by eslint.config.*.ts
  globals: '17.0.0',
  // Used by eslint.config.*.ts
  '@eslint/js': '9.39.2',
  // Used by eslint.config.*.ts
  '@eslint/json': '0.14.0',
  // Used by eslint.config.*.ts
  '@eslint/markdown': '7.5.1',
  // Used by eslint.config.*.ts
  '@html-eslint/eslint-plugin': '0.52.1',
  // Used as peerDependency of '@html-eslint/eslint-plugin'
  '@html-eslint/parser': '0.52.0',
  // Used by eslint.config.*.ts
  'eslint-config-prettier': '10.1.8',
  // Used by eslint.config.*.ts
  'eslint-plugin-functional': '9.0.2',
  // Used by eslint.config.*.ts
  'eslint-plugin-yml': '1.19.1',
  // Used by eslint.config.*.ts
  'typescript-eslint': '8.51.0',
  // Used by the lint script and by vscode and its plugins
  //oxlint: '1.36.0',
  // Used by oxlint with --type-aware flag
  //'oxlint-tsgolint': '0.10.0',
  // Used by the format script and by vscode and its plugins
  //oxfmt: '0.21.0',
};

// Add here all dependencies used by modules exported in index.ts.
export const configsPeerDependencies = {
  // Used by the test script and vscode and its plugins
  vitest: '4.0.16',
};

// Add here all devDependencies used by Config.anyPackage.ts, be it in scripts, github actions, installed config files... except those dependencies already in configsPeerDependencies
export const baseDevDependencies = {
  // Used as plugin by tsconfig.base.json
  '@effect/language-service': '0.56.0',
  // Used by tsconfig.docgen.json and tsconfig.others.json
  '@types/node': '24.10.1',
  // Used by the tscheck script and by vscode and its plugins
  '@typescript/native-preview': '7.0.0-dev.20260109.1',
  // Used as peerDependency of eslint, to run the examples scripts and by the update-config-files script
  jiti: '2.6.1',
  /* Used by the formatterConfig.ts file */
  'prettier-plugin-jsdoc': '1.8.0',
  /* Used by the formatterConfig.ts file. Prefer sorting imports with this plugin rather than with the vscode included functionality so imports will be sorted when calling pnpm format */
  'prettier-plugin-organize-imports': '4.3.0',
  // Used by tsconfig.base.json
  '@tsconfig/strictest': '2.0.8',
  // Used by the lint script, by vscode and its plugins and as type import by the linterConfig.ts file
  eslint: '9.39.2',
  // Used by the format script, by vscode and its plugins and as type import by the formatterConfig.ts file
  prettier: '3.7.4',
};

// Add here all devDependencies used by the sourcePackage Config instance, be it in scripts, github actions, installed config files...
export const packageSourceDevDependencies = {
  madge: '8.0.0',
  /* All packages use Effect and all may use @effect/experimental. @effect/experimental is included in the esm modules and should therefore be included as a dependency. But @effect/experimental is for debugging and performance optimization only. So the code that uses it must be removed or by-passed in prod. So this dependency must not be shipped in prod: it's a devDependency. */
  '@effect/experimental': '0.57.4',
  // At some point, rolldown will be default in vite. But not the case for the moment
  // Not necessary in all configurations but vite is installed by vitest in any case so better install it here
  vite: 'npm:rolldown-vite@7.3.0',
  // Not necessary in all configurations but best if shared when neeeded
  '@babel/core': '7.28.5',
  'babel-plugin-annotate-pure-calls': '0.5.0',
  '@babel/plugin-transform-export-namespace-from': '7.27.1',
  '@babel/plugin-transform-modules-commonjs': '7.27.1',
};

export const autoGeneratedFileWarning =
  ' ************** This file is automatically generated. Any modifications will be lost ************************\n\n';

export const githubActionTimeOut = 10;
