// This module must not import any external dependency. It must be runnable without a package.json
import { packageJsonFilename } from './constants.js';

export type Record<K extends string | symbol = string, V = unknown> = {
  [k in K]: V;
};

export type ReadonlyRecord<K extends string | symbol = string, V = unknown> = {
  readonly [k in K]: V;
};

export interface StringRecord extends Record<string, string> {}

export interface StringArray extends Array<string> {}

export interface PackageWithSourceConfigParameters {
  readonly description: string;
  readonly dependencies: Readonly<StringRecord>;
  readonly devDependencies: Readonly<StringRecord>;
  readonly peerDependencies: Readonly<StringRecord>;
  readonly examples: Readonly<StringArray>;
  readonly scripts: Readonly<StringRecord>;
  readonly environment: string;
  readonly buildMethod: string;
  readonly isPublished: boolean;
  readonly hasDocGen: boolean;
  readonly keywords: Readonly<StringArray>;
  readonly useEffectAsPeerDependency: boolean;
  readonly useEffectPlatform: string;
  readonly packagePrefix: string;
  readonly autogeneratedIndexTs: string;
  readonly autogeneratedImports: ReadonlyRecord;
}

export interface Config {
  readonly [key: string]: string | ReadonlyRecord;
  readonly [packageJsonFilename]: {
    readonly [key: string]: unknown;
    readonly name: string;
    readonly dependencies?: StringRecord;
    readonly devDependencies?: StringRecord;
    readonly peerDependencies?: StringRecord;
  };
}

export const isArray: (v: unknown) => v is Array<unknown> = Array.isArray;

export const isRecord = (v: unknown): v is Record =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

export const isStringRecord = (v: unknown): v is StringRecord =>
  isRecord(v) && Object.entries(v).filter(([, value]) => typeof value !== 'string').length === 0;

export const isStringArray = (v: unknown): v is StringArray =>
  isArray(v) && v.filter((value) => typeof value !== 'string').length === 0;

interface RepoBase {
  readonly name: string;
  readonly absolutePath: string;
}

interface PackageWithoutSource extends RepoBase {
  readonly type: 'TopRepo' | 'MonoRepo';
}

interface OnePackageRepo extends RepoBase {
  readonly type: 'OnePackageRepo';
  readonly isConfigsPackage: boolean;
}

interface SubRepo extends RepoBase {
  readonly type: 'SubRepo';
  readonly repoName: string;
}

export type Package = PackageWithoutSource | OnePackageRepo | SubRepo;
